run:
  timeout: 5m
  issues-exit-code: 1

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - errcheck
    - ineffassign
    - typecheck
    - gofmt
    - revive

issues:
  max-same-issues: 50
  exclude-use-default: false

output:
  formats:
    - format: github-actions
