blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/guyghost/constantine/tree/main/docs
    about: Check the documentation for guides and examples
  - name: 💬 Discussions
    url: https://github.com/guyghost/constantine/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Advisory
    url: https://github.com/guyghost/constantine/security/advisories/new
    about: Report security vulnerabilities privately
