name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees:
  - guyghost

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem or limitation you're experiencing
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: "I considered..."

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this affect?
      options:
        - Exchange Integration
        - Strategy Engine
        - Execution Agent
        - Risk Management
        - TUI Interface
        - Backtesting
        - Configuration
        - Documentation
        - CI/CD
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: checkboxes
    id: willing
    attributes:
      label: Contribution
      options:
        - label: I am willing to submit a PR for this feature
          required: false

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: Describe your use case in detail
      placeholder: "As a trader, I want to... so that..."
    validations:
      required: true

  - type: textarea
    id: technical
    attributes:
      label: Technical Details
      description: Any technical details or implementation suggestions?
      placeholder: "This could be implemented by..."

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups
