name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# Permissions minimales par défaut (principe du moindre privilège)
permissions:
  contents: read

# Annuler les exécutions précédentes pour la même branche
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: '1.24'
  CACHE_VERSION: v1

jobs:
  # Job 1: Validation du code (format, vet, mod)
  validate:
    name: Code Validation
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.23', '1.24']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: |
            go.sum
            go.mod

      - name: Verify go.mod and go.sum
        run: |
          go mod download
          go mod verify

      - name: Check gofmt
        run: |
          fmt_files=$(gofmt -l .)
          if [ -n "$fmt_files" ]; then
            echo "❌ Les fichiers suivants ne sont pas formatés avec gofmt:"
            echo "$fmt_files"
            exit 1
          fi
          echo "✅ Tous les fichiers sont correctement formatés"

      - name: Run go vet
        run: go vet ./...

      - name: Check for tidyness
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

      - name: Check documentation
        if: matrix.go-version == '1.24'
        run: |
          # Check that all exported functions/types have documentation
          go install golang.org/x/tools/cmd/godoc@latest
          
          # Simple check for missing documentation (can be enhanced)
          echo "Checking for undocumented exported symbols..."
          undoc=$(go doc -all ./... 2>&1 | grep -E "^package|^func|^type" | wc -l)
          echo "Found $undoc documented symbols"

  # Job 2: Tests avec coverage
  test:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.23', '1.24']
    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: |
            go.sum
            go.mod

      - name: Download dependencies
        run: go mod download

      - name: Load 1Password CLI
        if: env.OP_SERVICE_ACCOUNT_TOKEN != ''
        uses: 1password/load-secrets-action@v1
        with:
          export-env: false

      - name: Run tests
        run: |
          if [ -n "${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}" ]; then
            op run --env-file .env.op.template -- go test -v -race -coverprofile=coverage.out -covermode=atomic -timeout=10m ./...
          else
            go test -v -race -coverprofile=coverage.out -covermode=atomic -timeout=10m ./...
          fi

      - name: Check coverage threshold
        if: matrix.go-version == '1.24'
        run: |
          total_coverage=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          echo "Total coverage: ${total_coverage}%"
          
          # Minimum coverage threshold (configurable)
          threshold=40.0
          
          if (( $(echo "$total_coverage < $threshold" | bc -l) )); then
            echo "::error::Coverage ${total_coverage}% is below threshold ${threshold}%"
            exit 1
          fi
          echo "::notice::Coverage ${total_coverage}% meets threshold ${threshold}%"

      - name: Generate coverage report
        if: matrix.go-version == '1.24'
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage to Codecov
        if: matrix.go-version == '1.24'
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-go-${{ matrix.go-version }}
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage artifacts
        if: matrix.go-version == '1.24'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.out
            coverage.html
          retention-days: 30

  # Job 3: Linting
  lint:
    name: Linting
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: |
            go.sum
            go.mod

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62.0
          args: --config=.golangci.yml --timeout=10m
          skip-cache: false
          skip-pkg-cache: false
          skip-build-cache: false

  # Job 4: Build
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.23', '1.24']
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          # Exclure windows/arm64 car rarement utilisé
          - goos: windows
            goarch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: |
            go.sum
            go.mod

      - name: Download dependencies
        run: go mod download

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          # Build with version info and optimizations
          VERSION=$(git describe --tags --always --dirty)
          COMMIT=$(git rev-parse --short HEAD)
          BUILD_TIME=$(date -u '+%Y-%m-%d_%H:%M:%S')
          
          LDFLAGS="-s -w -X main.Version=${VERSION} -X main.Commit=${COMMIT} -X main.BuildTime=${BUILD_TIME}"
          
          go build -v -ldflags="${LDFLAGS}" -o bin/constantine-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/bot
          go build -v -ldflags="${LDFLAGS}" -o bin/backtest-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/backtest

      - name: Upload build artifacts
        if: matrix.go-version == '1.24'
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: bin/*
          retention-days: 7

  # Job 5: Sécurité - Vulnérabilités
  security:
    name: Security Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: |
            go.sum
            go.mod

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck ./...

      - name: Cache analysis results
        uses: actions/cache@v4
        with:
          path: ~/.cache/govulncheck
          key: govulncheck-${{ hashFiles('go.sum') }}-${{ env.CACHE_VERSION }}
          restore-keys: |
            govulncheck-${{ hashFiles('go.sum') }}-
            govulncheck-
