name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Verify gofmt
        run: |
          set -euo pipefail
          fmt_files=$(git ls-files '*.go')
          if [ -z "$fmt_files" ]; then
            exit 0
          fi
          unformatted=$(gofmt -l $fmt_files)
          if [ -n "$unformatted" ]; then
            echo "The following files are not gofmt'ed:"
            echo "$unformatted"
            exit 1
          fi

      - name: Download modules
        run: go mod download

      - name: Load 1Password CLI
        if: env.OP_SERVICE_ACCOUNT_TOKEN != ''
        uses: 1password/load-secrets-action@v1
        with:
          export-env: false

      - name: Run tests
        run: |
          if [ -n "${OP_SERVICE_ACCOUNT_TOKEN}" ]; then
            op run --env-file .env.op.template -- go test ./...
          else
            go test ./...
          fi

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          args: --config=.golangci.yml
