name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Verify gofmt
        run: |
          set -euo pipefail
          fmt_files=$(git ls-files '*.go')
          if [ -z "$fmt_files" ]; then
            exit 0
          fi
          unformatted=$(gofmt -l $fmt_files)
          if [ -n "$unformatted" ]; then
            echo "The following files are not gofmt'ed:"
            echo "$unformatted"
            exit 1
          fi

      - name: Download modules
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          args: --config=.golangci.yml
